version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errcheck
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      disable-default-exclusions: false
      exclude-functions:
        - io.Copy
        - (io.Closer).Close
        - (*os.File).Close
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
        - (*encoding/json.Decoder).Decode
formatters:
  enable:
    - gofmt
